### ISSUE TITLE
Color Issues in Light Theme

### ISSUE THREAD

**Issue by pomianowski** [lepoco/wpfui#13]
**Describe the bug**  
Many controls need to be tweaked in the Light Theme due to the fact that the default theme is black.

**Comment by MajorBoo** [comment]
The problem is that most of the controls need to be redone. WinUI 3 uses the border almost everywhere. I can show you an xaml example of a button that I was able to replicate from WinUI 3.

You copied the colors, that's a good start, but keep in mind that [ControlElevationBorderBrush](https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Common_themeresources_any.xaml#L462) is different for Light and Dark themes, so keeping them in the [same ](https://github.com/lepoco/wpfui/blob/main/WPFUI/Styles/Assets/Brushes.xaml) file won't work.

**Comment by Pomianowski** [comment]
@MajorBoo, feel free to send a PR with changed controls.

**Comment by MajorBoo** [comment]
@Pomianowski Umm, there's a problem, with this gradient (ControlElevationBorderBrush) in the Light theme... For some unknown reason, it only calculates to the height of one element (probably the one that loaded first). Here's an example if you apply it to borders of different heights...

![Capture4](https://user-images.githubusercontent.com/93913816/146430110-b7589fcb-e1b3-45b0-92ae-098c6ff5afe0.PNG)

**Comment by chucker** [comment]
This should be left open, IMHO. There are quite a number of color issues in the light theme.

For example:

<img width="118" alt="image" src="https://user-images.githubusercontent.com/20194/171355094-59db5cff-0b59-4c25-91b6-076a04a9d2ce.png">

<img width="109" alt="image" src="https://user-images.githubusercontent.com/20194/171355043-b406ca03-ac9f-4ac7-adc9-6e378f14c5ee.png">

The first is a screenshot from Windows Settings (ignore the different accent color).

The second and third are:

```xml
        <modernwpf:ToggleSwitch IsOn="True">On</modernwpf:ToggleSwitch>
        <wpfui:ToggleSwitch IsChecked="True">On</wpfui:ToggleSwitch>
```

The blue should be a darker shade, and the foreground should be white.
