### ISSUE TITLE
 Want to add navigation bar zoom function!

### ISSUE THREAD

**Issue by BlameTwo** [lepoco/wpfui#145]
1. I hope the left navigation bar can automatically adjust the width and icon size according to the window size, which is more suitable for small window navigation

2. I think we should add some small detail animations to make the program look more flexible.

**Comment by MajorXAML** [comment]
This will not work, the icons are already quite small and if you make them smaller they will be very blurry. Navigation for small screens is available in WinUI, something similar is done in modernwpf, but it would require thousands of lines of code to do it in wpfui. This is probably the most complicated control in the whole library.

**Comment by 123456fsdaf** [comment]
In that case, can you just make the expand button? Because I noticed that when the application is reduced to a certain extent, its navigation bar will account for a huge proportion, which is not beautiful. If you only use the expand button, you should avoid this situation and do not need adaptive layout.
