### ISSUE TITLE
Button Text color on Apperance

### ISSUE THREAD

**Issue by jasmeet21** [lepoco/wpfui#190]
The button text color is not consistent between primary and others ( success, caution, danger, etc). The primary color is always the opposite of other buttons and this may not look pretty when using it together. 

If primary meant to behave this way, could we have another appearance created e.g "Info" with similar to primary and correct color 

Light Mode( Primary foreground becomes white while other appearance foreground become black)
![image](https://user-images.githubusercontent.com/9377470/168414690-16696ce6-13b5-46d2-b233-28f21b6d607b.png)

Dark Mode ( Primary foreground becomes black while other appearance foreground become white)
![image](https://user-images.githubusercontent.com/9377470/168414718-679d67b3-4ec2-4a95-8ec4-138119674b35.png)

**Comment by pomianowski** [comment]
**Primary** is based on the system color, you are right that you we add **Info**. Because if your system color is for example purple, primary will be purple.
![image](https://user-images.githubusercontent.com/13592821/168425943-fc468185-8cf9-45fd-902c-ed493cd7a9ef.png)

As for the foreground color, we can set a constant specific to Warning and others, and the text color to Primary should be based on the brightness from the HSV palette, but this needs some implementation.
