### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Wlad57** [lepoco/wpfui#23]
Hi, sorry if this is a silly question, but I'm trying to port Navigation into a project on Net Framework 4.8. I'm using vs2022 and resharper, not sure what it's about, but I see a lot of warnings like:

"CS8603 Possible null reference return."
"CS8625 Cannot convert null literal to non-nullable reference type."
etc... 
it looks very like some of the code needs refactoring, is this true or am I missing something?

And one more thing, it looks like some of the Handlers won't be able to be compiled on nf4.8. Because they require version C# 9.0 or later. So I'm not sure if the library is ready to run on older versions of .net

**Comment by MajorBoo** [comment]
You get these warnings because they are enabled for your project, just remove this line:
`<Nullable>enable</Nullable>`

But yes, some refactoring would be nice :) For example, I don't quite understand why we need [IIconElement.cs](https://github.com/lepoco/wpfui/blob/main/WPFUI/Controls/IIconElement.cs) since we do get/set in each control separately 🤔

**Comment by Pomianowski** [comment]
> But yes, some refactoring would be nice :) For example, I don't quite understand why we need [IIconElement.cs](https://github.com/lepoco/wpfui/blob/main/WPFUI/Controls/IIconElement.cs) since we do get/set in each control separately 🤔

I use IIconElement to confirm that the element using the interface correctly implements all assumptions of the element with the Icon. And since different elements extends different classes, we can't just use inheritance.
