### ISSUE TITLE
Wrong background color on W11 Insider (22H2)

### ISSUE THREAD

**Issue by Xinnony** [lepoco/wpfui#271]
**Describe the bug**  
Hi, i find a problem with a background on Windows 11 22H2 (22621.169).
I not have this problem on 21H2 (tested with two different computer).

You can si this problem only when your wpf window is focused !

**To Reproduce**  
Just focus the WPF Window

**How can fix it**  
You can disable "Show accent in title and border window" on the Settings of Windows but the Background is Black.

**Screenshots**  
![image](https://user-images.githubusercontent.com/6058403/177766870-7c976535-e63e-4f47-b63d-892806b19a28.png)
![image](https://user-images.githubusercontent.com/6058403/177767050-0c217fa8-6b69-4d49-962d-130ba1aae8d8.png)

**On 21H2**  
![image](https://user-images.githubusercontent.com/6058403/177767274-19e25ea9-c9bd-4ca0-a3cc-69363dec441d.png)

**Comment by Xinnony** [comment]
Same on DEMO Apps with 1.2.7 version AND with the last devlopement version (commit 838cd35032e11d525585c8834ed79e01abf2d7ab)
![image](https://user-images.githubusercontent.com/6058403/177769654-cb8b0f8b-e456-4909-bb56-3a4efbc56322.png)

**Comment by pomianowski** [comment]
It seems  that non-client-area is properly transparent and client-area is overlapping the titlebar but is not over it. Black background looks like error when removing the client background for the Mica effect, and in second case, the titlebar should be 0 or still transparent. 
The solution is to either disable this effect (titlebar accent) or remove titlebar / give it zero height. Because although the original buttons are not visible, the core titlebar itself is still there and takes the accent color

**Comment by blakepell** [comment]
I can confirm that removing the Mica effect and changing it to `WindowBackdropType="None"` gets rid of the accent.

**Comment by ByronAP** [comment]
Titlebar showing blue is killing me too (just a bump for this issue)

**Comment by sappho192** [comment]
> Titlebar showing blue is killing me too, when changing themes at runtime the default backdrop is Mica. Adding the `Wpf.Ui.Appearance.BackgroundType.None` when applying the new theme seems to work.
> 
> EX: `Wpf.Ui.Appearance.Theme.Apply(Wpf.Ui.Appearance.ThemeType.Light, Wpf.Ui.Appearance.BackgroundType.None);`

This helped my problem. Thanks!

**Comment by Xinnony** [comment]
Thanks 👍🏻
