### ISSUE TITLE
Maximize button icon not updated

### ISSUE THREAD

**Issue by GuillaumeMiet** [lepoco/wpfui#37]
The Maximize button icon is not updated when the window is pin to the top of the screen and switch to maximised mode.

**Comment by Aelarion** [comment]
This is also true when using hotkeys:
- "Restore" icon persists when leaving maximized state with `Super+Down`
- "Maximize" icon persists when entering maximized state with `Super+Up`

In general, it looks like `TitleBar.IsMaximized` is not getting updated properly on any action that does not directly or indirectly call [`TitleBar.MaximizeWindow()`](https://github.com/lepoco/wpfui/blob/65101e5e7a3e591c6c109924915fe8725b1bdfd8/WPFUI/Controls/TitleBar.cs#L384).

An easy fix might be subscribing to the `ParentWindow.StateChanged` event. In that handler, we could do a sanity check on `TitleBar.IsMaximized` and if it mismatches with `ParentWindow.WindowState`, just manually assign it the correct value so that the icons update. This feels a bit hacky to me, but ultimately would avoid having to completely overhaul the functionality of the `TitleBar` control and would be fairly easy to implement. Only quirk might be figuring out when to subscribe so that `ParentWindow` can be set properly.

This sanity check logic also wouldn't have any clashes when clicking the buttons, since `Window.StateChanged` is raised **after** the the state is changed (https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.statechanged). So when clicking the buttons, the sanity check would just fall through.

Perhaps there's a better solution involving binding `IsMaximized` to the `ParentWindow.WindowState` with a value converter that takes into account if the `ParentWindow` is not set, but my WPF knowledge is more limited there (would likely involve some annoying refactoring too).

**Comment by Aelarion** [comment]
Just tried implementing my comment above by subscribing in the existing `TitleBar_Loaded` method, seems to do the trick at least for the few ways I tested:
- Drag window to top of screen to maximize
- `Super+Up` to maximize
- `Super+Down` to restore

![max-restore-fix](https://user-images.githubusercontent.com/38231674/150711717-b047687d-3da2-4b78-9204-5bab86431278.gif)

The one thing that I'm not totally sure how to handle is if there's some oddball case where the `ParentWindow` could change after the `TitleBar` control is loaded, without ever calling `TitleBar_Loaded` again. Could mean some whacky behavior if that happens and we don't unsub from `ParentWindow.StateChanged`. I'm not a WPF expert but I'm not sure that would be a reasonable use case to support.

If we're not concerned with the above, I can send in a PR. Don't want to overcomplicate things with submissions on different branches in case my previous PR is rejected, so I'll give that one a little bit to be reviewed before sending in another.

**Comment by Pomianowski** [comment]
Hey @Aelarion, seems your solution works very well for basic cases like dragging or hotkeys. If there are more problematic cases in the future then something can be done to improve. I think that's enough for now
