### ISSUE TITLE
Double-click sometimes incorrectly maximizes the application

### ISSUE THREAD

**Issue by pomianowski** [lepoco/wpfui#43]
**Describe the bug**  
Sometimes when you trigger the maximizing by double-clicking on the TitleBar, the application is immediately maximized and restored.

**To Reproduce**  
1. Open one or two demo app's
2. Several times maximize and restore using double-click / dragging from maximized window
3. See error

**Expected behavior**  
Double click always maximizes the application from its normal state.

**Screenshots**  

![Animation](https://user-images.githubusercontent.com/13592821/151060626-2307f355-7783-41ac-b583-7b59fa99c8c0.gif)

**Desktop:**  
 - OS: Windows 11 Education 22000.1.amd64fre.co_release.210604-1628
 - .NET: 6.0.101
 - Version: 1.2.2-prerelease133

**Additional context**  
#36 
/ Multimonitor setup - 3440x1440 (125%) [Landscape] + 1080x1920 (125%) [Portrait]

**Comment by pomianowski** [comment]
@Aelarion https://github.com/lepoco/wpfui/issues/36#issuecomment-1021215221 related

**Comment by Aelarion** [comment]
I'm having trouble reproducing this, but just looking through the code I think the `RootGrid.MouseDown` handler might be clashing with `RootGrid.MouseMove` handler: https://github.com/lepoco/wpfui/blob/a0795c3e2435c1564d8548814e7b2f9eb5734668/WPFUI/Controls/TitleBar.cs#L504-L510

Both of these handlers are looking for the mouse to be pressed, however the `MouseDown` handler is going to take priority since it will fire as soon as the button is down, whereas the `MouseMove` handler is going to wait until the mouse is moved by whatever amount of pixels the system decides is "enough" to fire, and the logic inside of that handler is to do nothing unless the left mouse button is pressed.

Since the `MouseDown` event will take priority, it is triggering the `ParentWindow.DragMove()` call as soon as the button is down. This may affect how the window messages are being sent for window states and such.

Looking at the `RootGrid.MouseDown` event -- I think we could quite easily just combine that into `RootGrid.MouseMove` handler, since it is already doing the left mouse button check anyway. The handler would essentially just turn into some simple short circuit logic:

- If left mouse button is not pressed, or parent window is null, do nothing
- If parent window is maximized --> do the restore magic to place the window under the mouse in a normal state (don't fire parent window drag yet)
- Finally, fire `ParentWindow.DragMove()` regardless of Maximized or Normal window states, since left mouse button is pressed and moving on the `TitleBar.RootGrid`

**Comment by Aelarion** [comment]
@pomianowski disregard my previous comment -- it's so much simpler...

To reproduce this issue, place the window towards the top of your screen, so that the TitleBar will be under your mouse when you double click it. Somewhere in here, this is triggering the `RootGrid.MouseMove` event, even though the mouse is not moving. As a result, it is triggering the "restore-drag" functionality without the mouse moving... 🤦
