### ISSUE TITLE
Question: How can I access page controls from another page?

### ISSUE THREAD

**Issue by Wlad57** [lepoco/wpfui#47]
So, I'm using the navigation with a frame (like in the demo) but I don't quite understand how to access a controls that is located on another page? like I have two pages, HomePage and SecondPage, HomePage has a HomeCheckBox how to access this checkbox from SecondPage 🤔

I don't use mvvm and maybe it's a dumb question. 😅

**Comment by Aelarion** [comment]
Unfortunately this is not really how WPF is supposed to work (obviously if you try hard enough you can do whatever you want lol). Your navigation control deals with Types, not instances (at least if you're using the demo and sort of standard way of doing things). For example, in the WPFUI.Demo `NavigationFluent` you'll see each of the items refers to a `Type`: https://github.com/lepoco/wpfui/blob/acfcedf846bfc0b546ca2b4c82686cb011f440c5/WPFUI.Demo/Views/Container.xaml#L61-L108

Because of the nature of dealing with Types, you're gonna have a decent amount of resistance trying to specifically manipulate controls from the parent window because of things like initialization of the page and other nuances that stem from this "type" vs. "instance" thing.

Again, there is not a necessarily "right" way to do everything (MVVM is a pattern, not gospel) -- however from the phrasing of your question it seems like you're a bit unfamiliar with WPF as a whole (nothing wrong with that of course, also please correct me if I'm wrong on that assessment). I'm not sure what you're looking to accomplish, but even if you are not using MVVM you might want to think about the logic behind why you're trying to do things like manipulate checkboxes or control contents from a window presenting a page. Typically pages are meant to be used similar to a webpages, sort of self-contained things where they are just presented from a frame or other container.

If you are super hell-bent on trying to do that, this answer from SO might point you in the right direction: https://stackoverflow.com/a/42072602/15744261

_**Side-note about issues:** these issues aren't typically for these types of questions so you may find it difficult to get concrete answers. They are more centered around issues with the package (e.g. something doesn't work, something should be done better, new feature request, etc.). StackOverflow and Reddit (subs like r/csharp, among other places) will be better places for these types of questions where people can walk you through solutions and thought processes behind them._

Good luck! :)

**Comment by Wlad57** [comment]
Thanks for the detailed answer!
