### ISSUE TITLE
Add new theme

### ISSUE THREAD

**Issue by Philigane** [lepoco/wpfui#544]
### Is your feature request related to a problem? Please describe

I wanna know how to add new theme. The ThemeType has only light/dark

### Describe the solution you'd like

A way to add new theme

**Comment by Lee-Lily-Lea** [comment]
There is a dictionary to map colors
For example, the background(bursh color) color of window is WindowBackground. When the theme is black, the value of WindowBackground is  (ff 000000). When the theme is light, the value of WindowBackground is  (ff f5f5f5)

The color of all elements such as controls should be semantic. Then the theme determines what color the corresponding semantic color should be.

You can copy the dictionary of the black or light theme in the source code and change the color of the brush to your favorite color

**Comment by Philigane** [comment]
Thank you for your answer

I already copied Black theme and personalized some colors. But how can i apply the theme ? I've tried to replace the URI in the current theme but the app is looking weird after that

**Comment by Lee-Lily-Lea** [comment]
You need to show me the screenshots of your key source code and effects.

I suggest you download Scr and view its demo.

**Comment by Philigane** [comment]
i've tried something like that. Atm i can't reproduce the exact pattern.
![image](https://user-images.githubusercontent.com/14936772/222379169-c3269b5f-2f2d-48db-a2f7-768ce155525f.png)

**Comment by Lee-Lily-Lea** [comment]
I use wpfui to use its color matching style, so I didn't adjust its color module, but I set up a similar function to adjust the color in order to consider the vision problems of some of my users
I wrote you a demo
This demo controls the color by writing a class
(I am not very familiar with xaml. The correct way is to make xaml instead of cs)
This demo realizes color matching switching by clicking the button
Here I only make a window background color, and the other models are the same
There are three things you need to do:
1. Create a class to manage colors (MyColorStyle. cs here)
2. Add this resource in the app (if you add it in the window layer, you will not be able to achieve cross-window control)
3. Create a setting page for users to click the button to switch styles

After you understand this demo, you can create your own color style in wpfui (but I doubt you need to modify the source code of wpfui)
![image](https://user-images.githubusercontent.com/78075553/222402680-b31a2585-14ab-4fd0-82a0-7fe851924a60.png)
![image](https://user-images.githubusercontent.com/78075553/222402735-0eec0b20-10cd-44ba-9ec3-d8b47a05ec23.png)

[WpfApp3.zip](https://github.com/lepoco/wpfui/files/10870301/WpfApp3.zip)

**Comment by pomianowski** [comment]
There are currently no plans to allow custom themes. As the creator of this library, I am not in favor of freedom of choice in terms of colors and I believe that applications should be as similar as possible to maintain the consistency of the OS's appearance. So I'm closing this thread as unplanned
