### ISSUE TITLE
Window Control Buttons Missing Icons

### ISSUE THREAD

**Issue by mastry** [lepoco/wpfui#6]
**Describe the bug**  
The window control buttons do not display correctly in the demo application. 

**To Reproduce**  
Run the demo application and not the buttons on the far right of the title bar.

![image](https://user-images.githubusercontent.com/1509152/144635730-618f62e7-a4a8-4695-964d-a11118b780ca.png)

**Expected behavior**  
Expected to see standard window control buttons like this:

![image](https://user-images.githubusercontent.com/1509152/144635858-cb9f10b7-4eb2-441e-97a7-c972b80fdd85.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: 6.0.100
 - Version: 1.1.0

This could be caused by the missing Fonts folder (it's referenced in the project, but not included in the source control):

![image](https://user-images.githubusercontent.com/1509152/144637231-b9f4a9bc-db6f-4b26-a7f0-9a3f1c4880cc.png)

**Comment by MikeKatsoulakis** [comment]
I fixed that by installing the Segoe Fluent Icons Microsoft font.

**Comment by Pomianowski** [comment]
Hey @mastry,
According to the [readme](https://github.com/lepoco/wpfui/blob/main/README.md), in order to use the icon pack from Windows 11 on version 10 and below you need to add the Segoe Fluent Icons font to your application resources.

Among other things, this font is responsible for the titlebar buttons.

https://github.com/lepoco/wpfui#segoe-fluent-icons

**Comment by Pomianowski** [comment]
Hey @mastry, in the latest commit, the icons from the font have been replaced with SVG icons and should work on Windows 10 without Segoe Fluent Icons.
