### ISSUE TITLE
Icons not showing up in controls. (Buttons, Textboxes, etc)

### ISSUE THREAD

**Issue by agonzalezrubio** [lepoco/wpfui#728]
### Describe the bug

Icons not showing up in controls (Buttons, Textboxes, etc.) both in design time and runtime. Also, the icon enum suggestions aren't showing up as well...

### To Reproduce

Try to set an icon in a ui control

### Expected behavior

Icon should be displayed.

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/113626269/7d453180-12a9-4fae-8d0c-3e8f806552dc)

### OS version

Windows 11

### .NET version

.NET 7.0

### WPF-UI NuGet version

3.0.0-preview.5

**Comment by Jan-GJ** [comment]
@agonzalezrubio  Hey, there is another way to display icons with this notation:
 `<ui:Button Appearance="Primary" Content="Add Person" Icon="{ui:SymbolIcon PersonAdd16}" />`

**Comment by agonzalezrubio** [comment]
Hey, thanks for your reply. The way you provided works!
Im gonna be using that notation in the meantime, but do you have any idea why the regular way and the suggestions arent working?

**Comment by pomianowski** [comment]
Hey @agonzalezrubio, thankts to the work of @IvanDmitriev1, there are now more ways to use icons in WPF UI. By default [`Button`](https://wpfui.lepo.co/api/Wpf.Ui.Controls.Button.html) uses [`IconElement`](https://wpfui.lepo.co/api/Wpf.Ui.Controls.IconElement.html). With this, you can use different kinds of icons on many controls.
```xaml
<ui:Button
  Icon="{ui:SymbolIcon PersonAdd16}" />
```
```xaml
<ui:Button Appearance="Primary" Content="WPF UI button with font icon">
  <ui:Button.Icon>
    <ui:SymbolIcon Symbol="Fluent24" />
  </ui:Button.Icon>
</ui:Button>
```

```xaml
<ui:Button Appearance="Primary" Content="WPF UI button with font icon">
  <ui:Button.Icon>
    <ui:ImageIcon Width="20" Source="pack://application:,,,/Assets/wpfui.png" />
  </ui:Button.Icon>
</ui:Button>
```

```xaml
<ui:Button Appearance="Primary" Content="WPF UI button with font icon">
  <ui:Button.Icon>
    <ui:FontIcon FontFamily="Segoe UI" Glyph="&#x1F308;" />
  </ui:Button.Icon>
</ui:Button>
```

And since 3.0.0-preview.6:
```xaml
<ui:Button
  Appearance="Primary"
  Content="WPF UI button with font icon"
  Icon="{ui:FontIcon '&#x1F308;'}" />
```

https://wpfui.lepo.co/api/Wpf.Ui.Controls.IconElement.html
https://wpfui.lepo.co/api/Wpf.Ui.Markup.SymbolIconExtension.html
