### ISSUE TITLE
AutoSuggestBox text property twoway binding error

### ISSUE THREAD

**Issue by agonzalezrubio** [lepoco/wpfui#731]
### Describe the bug

Typing into the AutoSuggestBox text with a binding gives me this error
```XAML
  <ui:AutoSuggestBox 
      x:Name="AdvancedTxtServer"
      Text="{Binding ServerSetup.ServerName, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, ValidatesOnDataErrors=True}"
      OriginalItemsSource="{Binding ServerList}" Icon="{ui:SymbolIcon Empty}"/>
```

```
This exception was originally thrown at this call stack:
    Wpf.Ui.Controls.AutoSuggestBox.TextPropertyChangedCallback(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs) in AutoSuggestBox.cs
    System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
    System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
    System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
    System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, ref System.Windows.EffectiveValueEntry, bool, bool, System.Windows.OperationType)
    System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, object, System.Windows.PropertyMetadata, bool, bool, System.Windows.OperationType, bool)
    System.Windows.DependencyObject.SetValue(System.Windows.DependencyProperty, object)
    MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(object, System.Xaml.XamlMember, object)
 ```
    
![image](https://github.com/lepoco/wpfui/assets/113626269/42c2487e-b655-43ba-8d2b-17a5e6816bfe)

### To Reproduce

Typing into the AutoSuggestBox text with a twoway binding

### Expected behavior

No error

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/113626269/42c2487e-b655-43ba-8d2b-17a5e6816bfe)

### OS version

Windows 11

### .NET version

.NET 7.0

### WPF-UI NuGet version

3.0.0-preview.5

**Comment by agonzalezrubio** [comment]
![image](https://github.com/lepoco/wpfui/assets/113626269/73225df3-fb92-4591-aa34-3e581088f872)

**Comment by Redvo** [comment]
This happens because [TextPropertyChangedCallback](https://github.com/lepoco/wpfui/blob/4dba295fa8d6afa079962cc49419d6dd2ea95d14/src/Wpf.Ui/Controls/AutoSuggestBoxControl/AutoSuggestBox.cs#L552C1-L566C6) is static and called before `TextBlock` is initialized in  [OnApplyTemplate](https://github.com/lepoco/wpfui/blob/4dba295fa8d6afa079962cc49419d6dd2ea95d14/src/Wpf.Ui/Controls/AutoSuggestBoxControl/AutoSuggestBox.cs#L285C4-L301C1).

The solution could be to store initial value in a private field if `TextBlock` is `null` and then set `TextBlock.Text` value to this field in `OnApplyTemplate`.

**Comment by Redvo** [comment]
This happens because [TextPropertyChangedCallback](https://github.com/lepoco/wpfui/blob/4dba295fa8d6afa079962cc49419d6dd2ea95d14/src/Wpf.Ui/Controls/AutoSuggestBoxControl/AutoSuggestBox.cs#L552C1-L566C6) is static and called before `TextBox` is initialized in  [OnApplyTemplate](https://github.com/lepoco/wpfui/blob/4dba295fa8d6afa079962cc49419d6dd2ea95d14/src/Wpf.Ui/Controls/AutoSuggestBoxControl/AutoSuggestBox.cs#L285C4-L301C1).

From documentation on Text property:
```
/// <remarks>
/// This property is not typically set in XAML.
/// </remarks>
```

So probably a `NULL` check would be sufficient to not get exception there. For workaround, remove that Text binding completely.

Now for your problem, what are you trying to achieve?

If you want to give AutoSuggestBox a default value, that is probably not a good idea. 

If you want to set Property in your ViewModel after some option is chosen, that is only possible in code-behind in `SuggestionChosen` event for now, as far as I discovered:

```xaml
<ui:AutoSuggestBox
  x:Name="AutoSuggestBox"
  SuggestionChosen="AutoSuggestBox_OnSuggestionChosen" ... />

```

```cs
private void AutoSuggestBox_OnSuggestionChosen(AutoSuggestBox sender, AutoSuggestBoxSuggestionChosenEventArgs args)
{
  ViewModel.ChosenOptionProperty = args.SelectedItem as MyOptionsItemType;
}
```

**Comment by agonzalezrubio** [comment]
Ohhhh, ok, thank you for your very useful response friend. Sorry I missed that! Lol.
