### ISSUE TITLE
Button.Icon not working when set in XAML

### ISSUE THREAD

**Issue by SickLab** [lepoco/wpfui#744]
### Describe the bug

The icon is not shown on the button when set in XAML. I tried with code behind and it worked.

In fact, even one of the 3 template solution where there is a button that said "Click Me" should have an icon when we check the XAML and it does not when we run the application.

### To Reproduce

Create a new Fluent Navigation project.

Run the project, Icon is not visible on the Click me! button.

According to the XAML:

<ui:Button Grid.Column="0" Command="{Binding ViewModel.CounterIncrementCommand, Mode=OneWay}" Content="Click me!" Icon="Fluent24" />

Should have Fluent24 icon.

Tried any other icon and none works.

### Expected behavior

An icon should be visible on the left side of the text.

Worked when set in code behind.

### OS version

Windows 11

### .NET version

.Net 7

### WPF-UI NuGet version

3.0.0.0 Preview 4

**Comment by agonzalezrubio** [comment]
Hey, I think this is fixed in the newest preview version. Apparently they were implementing new ways to use the icons, so the default option wasn't working for a while.

I ran in to the same issue and @Jan-GJ was kind enough to point the fix.
```xaml
<ui:Button Appearance="Primary" Content="Add Person" Icon="{ui:SymbolIcon PersonAdd16}" />
```

Link to my issue
https://github.com/lepoco/wpfui/issues/728
