### ISSUE TITLE
UiWindow style not applying. TargetType error.

### ISSUE THREAD

**Issue by MikeKatsoulakis** [lepoco/wpfui#8]
I am trying to use the 'UiWindow' Static Resource, but I am getting an error.
Error: 'Window' TargetType does not match the type of element 'Window'

**To Reproduce**  
1. Create a new WPF Window
2. Apply the Style="{StaticResource UIWindow}" property.

**Expected behavior**  
The windows' style to change to UiWindow.

**Desktop**  
 - OS:  Windows 10
 - .NET: net6.0-windows
 - Version: Stable 1.1.0 (Same error on the latest prerelease'39')

**Comment by MikeKatsoulakis** [comment]
Turns out its a WPF error. Depending on the Version of 'Window' that the library was compiled for. It's a designer only error. If you have the designer (.xaml file) closed, the project will compile and build fine.

**Comment by Inzaniity** [comment]
I have exactly the same issues with a project. It complains but still compiles. It's more of an annoyance than a "real" issue. Especially the designer doesn't show what I'm expecting it to show.  Every control that I add is translucent and I have to set the background of the underlying Grid to a color in order to see my controls. 

The error is as follows: `Error     XDG0062    TargetType "Window" does not match type of element "Window".`

(ignore the styling, I'm currently redesigning the app)
![devenv_JucZ6LxvPg](https://user-images.githubusercontent.com/17164019/150851310-c54cf4e2-1fe7-49c5-8156-eb8c6aab74d1.gif)

My XAML looks also to be fine
```
<Window
    x:Class="OBS_Source_Timer.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:wpfui="clr-namespace:WPFUI.Controls;assembly=WPFUI"
    xmlns:wpfuiCommon="clr-namespace:WPFUI.Common;assembly=WPFUI"
    Title="OBS Source Timer"
    Width="800"
    Height="450"
    Loaded="Window_Loaded"
    Style="{StaticResource UiWindow}"
    mc:Ignorable="d">
...
</Window>
```

What's also curious about this is that the demo project runs fine without any complaints whatsoever and the designer also works as expected.

Desktop
OS: Windows 11 Pro 21H2
.NET: net6.0-windows
Version: Stable 1.2.1
Visual Studio 2022

**Comment by Inzaniity** [comment]
Applying the Light theme in App.xml helps a lot with the issue, you can actually see and design your app that way without messing with background colors.
