### ISSUE TITLE
Too damn hard

### ISSUE THREAD

**Issue by Exterminator921** [lepoco/wpfui#82]
Why is it so complicated ? Why isn't there no tutorial ? Please make a tutorial. I personally request it. I had to leave WinUI because the lack of a designer is too hard for me, but this... this is incomprehensible for a newbie like me, Please help me. I'd use the old school WPF default UI rather than this if you don't make a tutorial. Why are those cool things always oriented towards experimented people ? I need help please read my message.

**Comment by MajorXAML** [comment]
First, learn the WPF basics. Youtube is your help.

**Comment by alxkalinin** [comment]
> Why is it so complicated ? Why isn't there no tutorial ? 

For me the WPF UI demo application is a good tutorial. You can get the source code from the GitHub, build application and check how the controls in the demo application are built.

WPFUI shares the common principle of the WPF applications and add in general the modern styles. If you have troubles with understanding the WPF, please check the following resources

- https://www.wpftutorial.net/
- https://www.wpf-tutorial.com/
- https://github.com/microsoft/WPF-Samples

And also please look at the [awesome wpf](https://github.com/Carlos487/awesome-wpf), collection of the references to the WPF.

**Comment by Exterminator921** [comment]
I already know the basics of WPF and I couldn't build WPF UI demo because it had bugs

**Comment by alxkalinin** [comment]
@[Exterminator921](https://github.com/Exterminator921) What kind of bug did you meet? On my machine build is successful.

**Comment by jasmeet21** [comment]
This is far more easier compared to WinUI 3, I'm newbie as well with < 1 year experience in wpf. his library have breath new live to my old traditional boring wpf ui.

The demo is build & run doesn't have any bugs, you could be doing something wrong; have you changed your startup project to demo ?

**Comment by Exterminator921** [comment]
No but I gave up i'm now using Microsoft.UI.XAML

**Comment by johngagefaulkner** [comment]
I've been developing with C# since 2007 (November of this year will make 15 years) but I only switched to WPF/UWP/XAML a little over 2 years ago. I would say it took me around 6 months to become "comfortable" with XAML, where I felt like I could easily create/recreate anything previously accomplished in Windows Forms. Fast forward to yesterday, I would've told you that I was entirely comfortable with XAML now ─ including multiple different design patterns like MVVM. 

Today, I came across this repo and it looks great at first glance but, after probably 2-3 hours of staring a source code for the Demo App on one screen and doing everything I can to get it to work in my test app on the other screen, I'm throwing in the flag. The CI workflows are failing ([and have been having some issues](https://github.com/lepoco/wpfui/actions)) so you can't build the Sample/Demo App, the "documentation" (and I'm using that term loosely) is literally just, "read the source code and figure it out yourself," and while the `App.xaml` section of [How to Use](https://github.com/lepoco/wpfui#-how-to-use) in the ReadMe works fine, the second step wouldn't work no matter what I tried ─ even going back to old branches that weren't failing CI and completely mirroring the project continued to fail. There are *obviously* some missing steps and─especially considering the amount of people here who "haven't had a problem"─I don't think it's too much to ask for documentation with at least *one* more step than [one of my favorite memes](https://pbs.twimg.com/media/Bs13i6LCcAAvwCf.jpg).

**Comment by Exterminator921** [comment]
Shit man we're just not the same... I was one month old when you starded C#
!

**Comment by pomianowski** [comment]
To be clear, I have been programming in WPF myself for only few years. This library is a hobby project and does not belong to the .NET Foundation.
And as always, free means **freedom**, not for free. If you want to improve something or help create documentation, feel free to help 😊

So far, there is no sponsor to even set up a page with docs.

If something needs to be corrected or done, it will someday be, but I would not make any demands here, and I believe this is where the discussion ends.

**Comment by pomianowski** [comment]
Anyone interested can help describe library here:
https://github.com/lepoco/wpfui/tree/documentation
