### ISSUE TITLE
The WebView2 control is not in the correct position after the page switch

### ISSUE THREAD

**Issue by ych98** [lepoco/wpfui#921]
### Describe the bug

When using the NavigationView control and the WebView2 control, switching pages will cause the WebView2 control position to jump, which is usually manifested as the distance of the WebView2 control jumping upwards by one TitleBar height after the switch.
Demo-WPF UI Gallery has the same problem: 
![image](https://github.com/lepoco/wpfui/assets/104015241/d17cd3de-1985-4400-87bd-9fc9e82dbc96)

### To Reproduce

All you need to do is switch to the page where the WebView2 control is located

### Expected behavior

Fix this jitter and get the WebView2 control where it should be

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/104015241/d17cd3de-1985-4400-87bd-9fc9e82dbc96)

### OS version

Windows 10

### .NET version

.net 6.0, 7.0

### WPF-UI NuGet version

3.0.0-preview.13

**Comment by pomianowski** [comment]
I think the reason for this is the 
```xml
<ui:NavigationView Transition="FadeInWithSlide" />
```
animation. At first, the contents of the window are slightly lower, and then they are animated upwards. Then, when the window is re-rendered, `WebView` corrects its position from its starting one.

When there is no animation (slide) the problem does not occur. WebView is not part of the WPF window and I don't know if there is a way to conveniently fix this. Due to this fact e probably won't focus on it

**Comment by ych98** [comment]
Thank you for your reply. When I set like this 
``` xml
<ui:NavigationView Transition="None" /> 
```
it solved the problem, although it was a symptom rather than a cure.
