### ISSUE TITLE
СontextMenu does not update color on theme switch. 

### ISSUE THREAD

**Issue by MajorXAML** [lepoco/wpfui#96]
Just checked the last [commit ](https://github.com/lepoco/wpfui/commit/ad683c56e0e27b3d84220059bb8c85d69ccc3272) and noticed Just checked out the latest commit and noticed that the context menu doesn't update the color when switching the theme.  🤔

![image](https://user-images.githubusercontent.com/93913816/158395210-ce213c9f-66dd-40aa-becc-f7261ae2f35f.png)

@ParzivalExe 
any ideas?

**Comment by ParzivalExe** [comment]
Well, I figured it out in the end and made a fix. The most important one was fixing the `BorderBrush`. This now properly changes whenever the Theme changes at runtime.

The Demo was a bit more problematic. The general problem was that I used the existing _ContextMenu_ and simply opened it by changing `ContextMenu.IsOpen = true` every time somebody pushed the _Button_. The problem with this approach is, that the _ContextMenu_ will not be rebuild after a Theme-Change during Runtime. This is no problem when using `ContextMenu` with a Right Click because apparently WPF does something different than just what I did which results in _ContextMenu_ actually being rebuild and the colors therefore changed accordingly. 
My dirty Fix (since I couldn't get the colors to change anyway else) is to simply create a new `ContextMenu` in CodeBehind every time the _Button_ is clicked. 
_This is oke in my opinion because this is simply a demo and the real usage of ContextMenu works without any workaround like this._
